force-app/main/default/objects/genesis__Applications__c.object
<CustomObject>
    <fields>
        <fullName>KYB_Performed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KYB Performed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KYB_Status__c</fullName>
        <label>KYB Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KYC_Performed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KYC Performed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KYC_Status__c</fullName>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>genesis__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APPROVED - APPROVED</fullName>
                </value>
                <value>
                    <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
                </value>
                <value>
                    <fullName>APPROVED - DOCUMENT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - CREDIT PULLED</fullName>
                </value>
                <value>
                    <fullName>NEW - ENTERED</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>NEW - IN CREDIT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - IN REVIEW</fullName>
                </value>
                <value>
                    <fullName>NEW - PRICING GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - SCORECARD GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - CHECKLIST GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>PULL CREDIT</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Passed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Failed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>Regulatory Checks Completed</fullName>
                </value>
                <value>
                    <fullName>Pending - Agent Portal</fullName>
                </value>
                <value>
                    <fullName>Pending - Underwriter</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Generated</fullName>
                </value>
                <value>
                    <fullName>Document Submission Required</fullName>
                </value>
                <value>
                    <fullName>Document Submission Completed</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending - Document Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/InvokeLexisNexisInstaID.cls
public class InvokeLexisNexisInstaID {
@Future(callout=true)
    public static void invokeLexisNexisCreditPull(Id applicationId) {
        system.debug(' Entered into invokeLexisNexisCreditPull with param size = ' );
        
        
        List<genesis__Applications__c> appList = [SELECT Id, 
                                                  genesis__Loan_Amount__c,
                                                  genesis__Account__c,
                                                  genesis__Status__c,
                                                  KYB_Performed__c,
                                                  KYB_Status__c,
                                                  KYC_Performed__c,
                                                  KYC_Status__c
                                                  FROM genesis__Applications__c
                                                  WHERE Id =:applicationId];
        
        //CreditCheckRequest request = new CreditCheckRequest();
        //request.retrieveFromDatabase = false;            
        Map<String,Object> borrowerValues = new Map<String,Object>();
        Map<String,Object> borrowerValues1 = new Map<String,Object>();
        borrowerValues.put('borrowerId',appList.get(0).genesis__Account__c);
        borrowerValues1.put('InputMap',borrowerValues);
        //borrowerValues1.addContextParameters('applicationId',app.Id);
        
        ints__Integration_Configuration__c integConfig = [ SELECT id , name ,ints__Integration_Service__c,ints__Type__c
                                                          FROM ints__Integration_Configuration__c
                                                          WHERE ints__Integration_Service__c='Credit Check' ] ;
        system.debug('name ='+integConfig.name);  
        system.debug('borrowerValues1 ='+borrowerValues1);       
        
        ints.AbstractMockService   mc  = ints.APIFactory.getPassthroughService();
        ints.IntegrationResponseObject responseObject =  mc.runPassthroughService(borrowerValues1,integConfig.ints__Integration_Service__c,'');
        system.debug('responseObject.responseStore Map ='+responseObject.responseStore);
        
        }

}