force-app/main/default/objects/genesis__Applications__c.object
<CustomObject>
    <fields>
        <fullName>KYB_Performed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KYB Performed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KYB_Status__c</fullName>
        <label>KYB Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KYC_Performed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KYC Performed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KYC_Status__c</fullName>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>genesis__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APPROVED - APPROVED</fullName>
                </value>
                <value>
                    <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
                </value>
                <value>
                    <fullName>APPROVED - DOCUMENT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - CREDIT PULLED</fullName>
                </value>
                <value>
                    <fullName>NEW - ENTERED</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>NEW - IN CREDIT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - IN REVIEW</fullName>
                </value>
                <value>
                    <fullName>NEW - PRICING GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - SCORECARD GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - CHECKLIST GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>PULL CREDIT</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Passed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Failed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>Regulatory Checks Completed</fullName>
                </value>
                <value>
                    <fullName>Pending - Agent Portal</fullName>
                </value>
                <value>
                    <fullName>Pending - Underwriter</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Generated</fullName>
                </value>
                <value>
                    <fullName>Document Submission Required</fullName>
                </value>
                <value>
                    <fullName>Document Submission Completed</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending - Document Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/CL_PB_JourneyOptimizer.cls
global class CL_PB_JourneyOptimizer{

    @InvocableMethod
    global static void cl_pb_journeyOptimizerCheck(List<Id> appId){
    
        List<genesis__Applications__c> updateApp = new List<genesis__Applications__c>();
        List<genesis__Applications__c> appList = [SELECT Id, 
                                                         genesis__Loan_Amount__c,
                                                         genesis__Status__c,
                                                         KYB_Performed__c,
                                                         KYB_Status__c,
                                                         KYC_Performed__c,
                                                         KYC_Status__c
                                                    FROM genesis__Applications__c
                                                   WHERE Id IN :appId];
                                                       
        Map<Id, genesis__Rule__c> mapRules = new Map<Id, genesis__Rule__c>([SELECT Id,
                                                                                   Name,        
                                                                                   genesis__Message_failure__c
                                                                              FROM genesis__Rule__C
                                                                             WHERE Name = :Label.CL_Journey_Optimizer_Checks
                                                                               AND genesis__Enabled__c = true
                                                                           ]);
                                                                           
        for(genesis__Applications__c app : appList){
          List<genesis__Checklist__c> checkList = genesis.RulesAPI.evaluateRules(app, mapRules.values(), false, false);

            String result = '';
            for(genesis__Checklist__c checklistObj: checkList){
                if(!checklistObj.genesis__Result__c){
                    result += mapRules.get(checklistObj.genesis__Rule__c).genesis__Message_failure__c + '\r\n';
                }
            }          
            
            System.debug('CL Journey Optimizer Rule Result = '+result);
            if(!String.isBlank(result)){    //if(app.genesis__Loan_Amount__c < 2000){
                app.genesis__Status__c = 'Document Submission Required';
                
                updateApp.add(app);
             }
             else{


             }          
        }
        update updateApp;
    }
}