force-app/main/default/objects/genesis__Applications__c.object
<CustomObject>
    <fields>
        <fullName>genesis__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APPROVED - APPROVED</fullName>
                </value>
                <value>
                    <fullName>APPROVED - CONVERTED TO CONTRACT</fullName>
                </value>
                <value>
                    <fullName>APPROVED - DOCUMENT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - CREDIT PULLED</fullName>
                </value>
                <value>
                    <fullName>NEW - ENTERED</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>NEW - IN CREDIT CHECK</fullName>
                </value>
                <value>
                    <fullName>NEW - IN REVIEW</fullName>
                </value>
                <value>
                    <fullName>NEW - PRICING GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - SCORECARD GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - CHECKLIST GENERATED</fullName>
                </value>
                <value>
                    <fullName>NEW - VEHICLE VALUATION REQUIRED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
                <value>
                    <fullName>PULL CREDIT</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Passed</fullName>
                </value>
                <value>
                    <fullName>TruVue01 - Failed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Passed</fullName>
                </value>
                <value>
                    <fullName>Lexis Nexis - Business InstaID - Failed</fullName>
                </value>
                <value>
                    <fullName>Regulatory Checks Completed</fullName>
                </value>
                <value>
                    <fullName>Pending - Agent Portal</fullName>
                </value>
                <value>
                    <fullName>Pending - Underwriter</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Generated</fullName>
                </value>
                <value>
                    <fullName>Document Submission Required</fullName>
                </value>
                <value>
                    <fullName>Document Submission Completed</fullName>
                </value>
                <value>
                    <fullName>Approved - Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending - Document Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>portal_stage__c</fullName>
        <label>portal stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer_Applies_Loan_Details</fullName>
                </value>
                <value>
                    <fullName>Customer_Applies_Personal_Info</fullName>
                </value>
                <value>
                    <fullName>Customer_Applies_Approved</fullName>
                </value>
                <value>
                    <fullName>Customer_Applies_Denied</fullName>
                </value>
                <value>
                    <fullName>docusign_signed</fullName>
                </value>
                <value>
                    <fullName>webster_session_timedOut</fullName>
                </value>
                <value>
                    <fullName>close_deal</fullName>
                </value>
                <value>
                    <fullName>Failure_wrap</fullName>
                </value>
                <value>
                    <fullName>Pending_Underwriter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/CLS_DocVerification.cls
global without sharing class CLS_DocVerification implements clcommon.PortalCustomRemoteAPI1{
   
    global clcommon.Response invokeAction(String componentStrName, String[] disclosureNames, Map<String, Object> params) {
        clcommon.Response res;
        try{
            if(params != null){
                system.debug('--params--'+params );
                String AppId = (String) params.get('applicationId');
                //String SelectedOfferId = (String) params.get('SelectedPaymentPlan');
                //String uniqueIdentifier = (String)params.get(CLS_PortalAPIConstants.UNIQUE_IDENTIFIER); 
                if(true){
                    List<genesis__Applications__c> appList = [SELECT id 
                                                              FROM genesis__Applications__c
                                                              WHERE id = : AppId  
                                                              ORDER BY CreatedDate asc limit 1];   
                    if(appList != null && appList.size() > 0){
                        res = setSuccessResponse(appList);
                    } else {
                        res = CLS_PortalUtils.setResponse(clcommon.Constants.ERROR, clcommon.Constants.API_EXCEPTION, 'Contract not found');
                    }                                 
                } else {
                    String errorMessage = CLS_PortalAPIConstants.ERROR_MESSAGE_PARAM_NOT_FOUND;
                    res = CLS_PortalUtils.setResponse(clcommon.Constants.ERROR, clcommon.Constants.API_EXCEPTION, errorMessage);
                }
            } else {
                String errorMessage = CLS_PortalAPIConstants.ERROR_MESSAGE_PARAM_NOT_FOUND;
                res = CLS_PortalUtils.setResponse(clcommon.Constants.ERROR, clcommon.Constants.API_EXCEPTION, errorMessage);
            }
        } catch(Exception e) {   
            res = CLS_PortalUtils.setResponse(clcommon.Constants.ERROR, clcommon.Constants.API_EXCEPTION, CLS_PortalAPIConstants.ERROR_MESSAGE_SOMETHING_WENT_WRONG);
        }
        return res;
    }
    private clcommon.Response setSuccessResponse( List<genesis__Applications__c> AppUpdateList){
        clcommon.Response res = new clcommon.Response();
        system.debug('--AppUpdateList--'+AppUpdateList);
       
        //AppUpdateList[0].genesis__Status__c = 'Offer Accepted';
        AppUpdateList[0].Portal_Stage__c = 'docusign_signed';
        update appUpdateList[0];
                                                                 

        Map<String,Object> fields = createResponseMap(appUpdateList[0]);
        
        List<clcommon.PortalCustomRemoteActionRecord> respList = new List<clcommon.PortalCustomRemoteActionRecord>();
        respList.add(new clcommon.PortalCustomRemoteActionRecord(CLS_PortalAPIConstants.KEY_RESPONSE, fields));
        res = clcommon.PortalActions.getCustomRemoteActionResponse(respList);
        res.status = clcommon.Constants.SUCCESS;
        return res;
    }
    
    private Map<String,Object> createResponseMap(genesis__Applications__c app){
        Map<String,Object> fields = new Map<String,Object>();
        //List<ContentDocumentLink> contentDoc = [Select id, ContentDocumentId, ContentDocument.LatestPublishedVersionId from ContentDocumentLink where LinkedEntityId = :app.Id limit 1];
        Attachment attachTest = [select id from Attachment where name ='testingDoc.pdf' limit 1];
        if(app.Portal_Stage__c != null){
            fields.put(CLS_PortalAPIConstants.PORTALSTAGE, app.Portal_Stage__c);
            //if(!attachTest)
                fields.put('AttachedDoc',attachTest.Id);
        }
        system.debug('--fields--'+fields);
        return fields;
    }
}